// client2/src/components/Player/ActivityCard.jsx
import { useParams } from "react-router";
import { Avatar, Card, Col, Image, Row } from "antd";
import { CheckCircleTwoTone, CloseCircleTwoTone } from "@ant-design/icons";
import { encodeName, formattedDates } from "../../utils/utils";
import { Link } from "react-router-dom";
import WinnerScore from "../Global/WinnerScore";

export default function ActivityCard({ event, year }) {
  const { pname, pid } = useParams();
  const { Meta } = Card;
  const eventDetails = event.scores[0].match.round.event;

  const currencies = {
    AUD: "A$",
    USD: "$",
    GBP: "£",
    EUR: "€",
  };

  const rounds = {
    "Round of 128": "R128",
    "Round of 64": "R64",
    "Round of 32": "R32",
    "Round of 16": "R16",
    Quarterfinals: "QF",
    Semifinals: "SF",
    Final: "F",
  };

  const title = (
    <div>
      <div>
        {eventDetails.sponsor_name && (
          <span>{eventDetails.sponsor_name} | </span>
        )}
        {eventDetails.tournament.name}
      </div>
      <div>
        {formattedDates(eventDetails.start_date, eventDetails.end_date)} |{" "}
        {eventDetails.venue.city}, {eventDetails.venue.country.name}
      </div>
    </div>
  );

  const extra = (
    <div>
      <div>{eventDetails.category}</div>
      <div>
        {eventDetails.surface.environment} {eventDetails.surface.surface}
      </div>
    </div>
  );

  const description = (
    <div className="flex">
      {event.seed && <div>Seed: {event.seed}</div>}
      {event.status && <div>Status: {event.status}</div>}
      <div>Points: {event.points}</div>
      <div>Rank: {event.rank}</div>
      <div>
        Prize Money: {currencies[eventDetails.currency]}
        {event.pm}
      </div>
    </div>
  );

  const entryInfo = (entry) => {
    if (entry.seed && entry.status) {
      return `(${entry.seed} ${entry.status})`;
    } else if (entry.seed) {
      return `(${entry.seed})`;
    } else if (entry.status) {
      return `(${entry.status})`;
    }
  };
  return (
    <Card title={title} extra={extra}>
      {event.scores.map((match) => {
        const player = match.match.p1?.player ? match.match.p2 : match.match.p1;
        const opponent = match.match.p1?.player
          ? match.match.p1
          : match.match.p2;
        return (
          <Row>
            <Col span={1}>{rounds[match.match.round.round]}</Col>
            <Col span={1}>
              {opponent.player && (
                <Image
                  alt={opponent.player?.player.country.name}
                  src={`/flags/${opponent.player?.player.country.id}.svg`}
                  className="rounded"
                />
              )}
            </Col>
            <Col span={2}>
              {match.match.incomplete !== "B" && (
                <Avatar
                  alt={opponent.player?.player?.full_name}
                  src={`https://www.atptour.com/-/media/alias/player-headshot/${opponent.player?.player?.id}`}
                  className="border-zinc-300 mx-2"
                />
              )}
            </Col>
            <Col span={10}>
              {match.match.incomplete === "B" ? (
                "BYE"
              ) : (
                <div>
                  <Link
                    className="hover-link"
                    to={`/players/${encodeName(
                      opponent.player?.player?.full_name
                    )}/${opponent.player?.player?.id}`}
                  >
                    {opponent.player?.player?.full_name}
                  </Link>{" "}
                  {(opponent.player.seed || opponent.player.status) && (
                    <small>{entryInfo(opponent.player)}</small>
                  )}
                </div>
              )}
            </Col>
            <Col span={1}>
              {match.match.incomplete !== "B" && opponent.player.rank}
            </Col>
            <Col span={1}>
              {match.match.winner.player.player.id === pid ? (
                <CheckCircleTwoTone twoToneColor="#52c41a" />
              ) : (
                <CloseCircleTwoTone twoToneColor="#b91c1c" />
              )}
            </Col>
            <Col span={5}>
              <Link
                className="hover-link"
                to={`/tournaments/${encodeName(eventDetails.tournament.name)}/${
                  eventDetails.tournament.id
                }/${year}/${eventDetails.id}/${match.match.match_no}`}
              >
                <WinnerScore winner={player} loser={opponent} />
              </Link>
            </Col>
            <Col span={3}>
              {opponent?.player && (
                <Link
                  className="hover-link"
                  to={`/h2h/${pname}/${pid}/${encodeName(
                    opponent.player.player.full_name
                  )}/${opponent?.player.player.id}`}
                >
                  H2H
                </Link>
              )}
            </Col>
          </Row>
        );
      })}
      <Meta description={description} />
    </Card>
  );
}

// client/src/components/Player/ActivityCard.vue
<script setup lang="ts">
import type { Activity } from '@/utils/interfaces';
import { category, encodeName, formattedDates, formatCurrency } from '@/utils/functions';
import MatchRow from './MatchRow.vue';

const props = defineProps<{
    id: string
    name: string
    event: Activity
}>()
</script>

<template>
    <v-card
        class="my-5 text-zinc-300 bg-indigo-900"
        variant="text"
        rounded="xl"
    >
        <v-container>
            <v-row>
                <v-col
                    class="flex items-center ml-5"
                    cols="2"
                >
                    <v-img
                        v-if="event.node.category"
                        :src="category(event.node.category)"
                        :alt="event.node.category"
                    />
                </v-col>
                <v-col>
                    <v-card-title>
                        <router-link
                            class="hover-link"
                            :to="{name: 'Tournament', params: {name: encodeName (event.node.tournament.name), id: event.node.tournament.id}}"
                        >
                            {{ event.node.tournament.name }}
                        </router-link>
                        <span
                            v-if="event.node.sponsor_name"
                            class="text-zinc-400"
                        >
                            | {{ event.node.sponsor_name }}
                        </span>
                    </v-card-title>
                    <v-card-subtitle>{{ event.node.venue.city }}, {{ event.node.venue.country.name }}</v-card-subtitle>
                    <v-card-subtitle>{{ event.node.surface.environment }} {{ event.node.surface.surface }} <span v-if="event.node.surface.hard_type">({{ event.node.surface.hard_type }})</span> | {{ formattedDates(event.node.start_date, event.node.end_date) }}</v-card-subtitle>
                </v-col>
            </v-row>
            <v-row>
                <v-col>
                    <v-table
                        class="bg-transparent"
                    >
                        <thead>
                            <tr
                                class="text-xs lg:text-sm"
                            >
                                <th
                                    class="!text-center !font-bold"
                                >
                                    Round
                                </th>
                                <th
                                    class="!font-bold"
                                >
                                    Opponent
                                </th>
                                <th
                                    class="!text-center !font-bold"
                                >
                                    Rank
                                </th>
                                <th />
                                <th
                                    class="!font-bold"
                                >
                                    Score
                                </th>
                                <th />
                            </tr>
                        </thead>
                        <tbody>
                            <MatchRow
                                v-for="match in event.node.matches"
                                :key="match.match_no"
                                :match
                                :id
                                :name
                                :players="event.node.playersConnection.edges"
                            />
                        </tbody>
                    </v-table>
                </v-col>
            </v-row>
            <v-row>
                <v-col
                    class="text-zinc-300 text-xs lg:text-sm text-center sm:flex"
                >
                    <div
                        v-if="event.properties.seed"
                        class="small"
                    >
                        seed: {{ event.properties.seed }}
                    </div>
                    <div
                        v-if="event.properties.status"
                        class="mx-2 small"
                    >
                        entry type: {{ event.properties.status }}
                    </div>
                    <div
                        v-if="event.properties.rank"
                        class="mx-2 small"
                    >
                        rank: {{ event.properties.rank }}
                    </div>
                    <div
                        v-if="event.properties.points"
                        class="mx-2 small"
                    >
                        points: {{ event.properties.points }}
                    </div>
                    <div
                        v-if="event.properties.pm"
                        class="mx-2 small"
                    >
                        prize money: {{ formatCurrency(event.node.currency, event.properties.pm) }}
                    </div>
                </v-col>
            </v-row>
        </v-container>
    </v-card>
</template>
