// client/src/components/Player/PlayerBreadcrumbs.vue
<script setup>
import { useRoute } from 'vue-router';
import { unencodeName } from '@/utils/functions';

// Variables
const props = defineProps(['name', 'id'])
const route = useRoute()
const pages = [{ name: 'player', title: 'Details' }, { name: 'activity', title: 'Activity' }, { name: 'titles', title: 'Titles and Finals' }, { name: 'index', title: 'Win-Loss Index' }, { name: 'stats', title: 'Stats' }]
</script>

<template>
    <a-breadcrumb>
        <a-breadcrumb-item>
            <router-link :to="{ name: 'home' }">Home</router-link>
        </a-breadcrumb-item>
        <a-breadcrumb-item>
            {{ unencodeName(name) }}
            <template #overlay>
                <a-menu>
                    <template v-for="(page, index) in pages" :key="index">
                        <a-menu-item v-if="route.name !== page.name">
                            <router-link :to="{ name: page.name }">{{ page.title }}</router-link>
                        </a-menu-item>
                    </template>
                </a-menu>
            </template>
        </a-breadcrumb-item>
    </a-breadcrumb>
</template>

// client/src/components/Player/PlayerBreadcrumbs.jsx
import { Breadcrumb } from "antd";
import { unencodeName } from "../../utils/utils";

export default function PlayerBreadcrumbs({ pname, pid }) {
  const breadcrumbs = [
    {
      title: "Home",
      key: "1",
      href: "/",
    },
    {
      title: unencodeName(pname),
      key: "2",
    },
    {
      title: "Overview",
      key: "3",
      href: `/players/${pname}/${pid}`,
      menu: {
        items: [
          {
            path: "/activity",
            title: "Activity",
          },
          {
            path: "/titles-and-finals",
            title: "Titles and Finals",
          },
          {
            path: "/wl-index",
            title: "Win-Loss Index",
          },
          {
            path: "/stats",
            title: "Stats",
          },
        ],
      },
    },
  ];
  return <Breadcrumb items={breadcrumbs} />;
}
