// tennishistory/components/players/player-details.vue
<script setup lang="ts">
const { player } = defineProps<{ player: PlayerDetailsType }>()

const playerDetails = computed(() => [
  { title: "Career High", value: player.ch ? `${player.ch} (${player.ch_date})` : "—" },
  { title: "Win-Loss", value: player.wl },
  { title: "Titles", value: player.titles },
  { title: "Prize Money", value: `$${player.pm}` },
  { title: "Age", value: player.age ? `${player.age} years (${player.dod ? `${player.dob} - ${player.dod}` : player.dob})` : "Unknown" },
  { title: "Height", value: player.height ? `${player.height} cm (${convertToFt(Number(player.height))})` : "Unknown" },
  { title: "Plays", value: player.rh ? handedness(player.rh) : "Unknown" },
  { title: "Backhand", value: player.bh ? `${player.bh}-Handed` : "Unknown" },
  { title: "Hall of Fame Induction", value: player.hof ?? "—" }
])
</script>

<template>
  <div class="w-full flex flex-col">
    <div class="h-(--ui-header-height) flex items-center border-b border-(--ui-border) px-4 sm:px-6 gap-1.5 mb-5">
      <h1 class="flex items-center gap-1.5 font-semibold text-(--ui-text-highlighted)">Details</h1>
    </div>
    <u-page-grid class="lg:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">
      <u-page-card
        v-for="detail in playerDetails"
        :key="detail.title"
        :title="detail.title"
        :description="detail.value"
        spotlight
        variant="outline"
      />
      <u-page-card
        :title="player.coaches.length === 1 ? 'Coach' : 'Coaches'"
        spotlight
        variant="outline"
      >
        <template #description>
          <template
            v-if="player.coaches.length > 0"
            v-for="coach in player.coaches"
            :key="coach.id"
          >
            <u-link
              v-if="coach.name"
              class="hover-link"
              :to="{ name: 'player', params: { name: useChangeCase(coach.name, 'kebabCase').value, id: coach.id } }"
              prefetch-on="interaction"
            >
              {{ coach.name }}
            </u-link>
            <template v-else>{{ coach.id }}</template>
          </template>
          <template v-else>—</template>
        </template>
      </u-page-card>
      <u-page-card
        v-if="player.countries.length > 0"
        class="col-span-2"
        title="Previous Representations"
        spotlight
        variant="outline"
      >
        <template #description>
          <div
            v-for="country in player.countries"
            :key="country.id"
            class="grid grid-cols-3 gap-2"
          >
            <flag-icon :country="country" />
            <span>{{ country.name }}</span>
            <span>{{ country.dates }}</span>
          </div>
        </template>
      </u-page-card>
    </u-page-grid>
  </div>
</template>

// client2/src/components/Player/PlayerDetails.jsx
import { Card, Col, Descriptions, Image, Row, Statistic } from "antd";
import { DateTime } from "luxon";
import {
  convertToFt,
  encodeName,
  formatDate,
  smallDate,
} from "../../utils/utils";
import { Link } from "react-router-dom";

export default function PlayerDetails({ player }) {
  const { Meta } = Card;
  console.log(player);

  return (
    <>
      <Row justify="space-evenly" gutter={6}>
        <Col span={6}>
          <Card className="text-center h-full flex flex-col justify-between">
            <Statistic title="Career High" value={player.career_high} />
            <Meta description={formatDate(player.ch_date)} />
          </Card>
        </Col>
        <Col span={6}>
          <Card className="h-full flex flex-col justify-between">
            <Statistic
              title="Win-Loss"
              value={`${player.win}—${player.loss}`}
              className="text-center"
            />
          </Card>
        </Col>
        <Col span={6}>
          <Card className="h-full flex flex-col justify-between">
            <Statistic
              title="Titles"
              value={player.titles}
              className="text-center"
            />
          </Card>
        </Col>
        <Col span={6}>
          <Card className="h-full flex flex-col justify-between">
            <Statistic
              title="Prize Money"
              prefix="$"
              value={player.pm_USD}
              className="text-center"
            />
          </Card>
        </Col>
      </Row>
      <Descriptions
        colon={false}
        className="my-10 text-center"
        bordered
        layout="vertical"
        size="middle"
      >
        <Descriptions.Item label="Country">
          <div className="flex items-center justify-normal">
            <div className="w-10 mr-2">
              <Image
                alt={player.countryConnection.edges[0].node.name}
                src={`/flags/${player.countryConnection.edges[0].node.id}.svg`}
                className="rounded-lg"
              />
            </div>
            <div className="ml-2">
              {player.countryConnection.edges[0].node.name}
            </div>
          </div>
        </Descriptions.Item>
        <Descriptions.Item label="Active">
          {player.turned_pro && player.retired ? (
            <div>
              <div>{player.retired.id - player.turned_pro.id} years</div>
              <div>
                {player.turned_pro.id}-{player.retired.id}
              </div>
            </div>
          ) : player.turned_pro ? (
            <div>
              <div>
                {parseInt(DateTime.now().year) - player.turned_pro.id + 1} years
              </div>
              <div>{player.turned_pro.id}-present</div>
            </div>
          ) : (
            "—"
          )}
        </Descriptions.Item>
        <Descriptions.Item label="Age">
          {player.dob ? (
            <div>
              <div>
                {Math.floor(
                  Math.abs(
                    DateTime.fromISO(player.dob).diffNow("years").toObject()
                      .years
                  )
                )}
              </div>
              <div>({formatDate(player.dob)})</div>
            </div>
          ) : (
            "—"
          )}
        </Descriptions.Item>
        <Descriptions.Item label="Height">
          <div>{player.height_cm}cm</div>
          <div>{convertToFt(player.height_cm)}</div>
        </Descriptions.Item>
        <Descriptions.Item label="Plays">
          {player.rh === true
            ? "Right-handed"
            : player.rh === false
            ? "Left-handed"
            : "—"}
        </Descriptions.Item>
        <Descriptions.Item label="Backhand">
          {player.bh1 === true
            ? "One-handed"
            : player.bh1 === false
            ? "Two-handed"
            : "—"}
        </Descriptions.Item>
        <Descriptions.Item label="Previous Representations" span={2}>
          {player.prev_countriesConnection.edges.length === 0 && "—"}
          {player.prev_countriesConnection.edges.length > 0 &&
            player.prev_countriesConnection.edges.map((country) => (
              <div className="flex items-center justify-start">
                <div className="w-10 mr-2 my-3">
                  <Image
                    alt={country.node.name}
                    src={`/flags/${country.node.id}.svg`}
                    className="rounded-lg"
                  />
                </div>

                <div className="mx-2 w-48">{country.node.name}</div>
                <div className="mx-2">
                  {smallDate(country.properties.start_date)}-
                  {smallDate(country.properties.end_date)}
                </div>
              </div>
            ))}
        </Descriptions.Item>
        <Descriptions.Item
          label={player.coaches.length === 1 ? "Coach" : "Coaches"}
        >
          {player.coaches.length > 0 &&
            player.coaches.map((coach) => (
              <div key={coach.id}>
                {coach.first_name ? (
                  <Link
                    className="hover-link"
                    to={`/players/${encodeName(coach.full_name)}/${coach.id}`}
                  >
                    {coach.full_name}
                  </Link>
                ) : (
                  coach.id
                )}
              </div>
            ))}
          {player.coaches.length === 0 && "—"}
        </Descriptions.Item>
      </Descriptions>
    </>
  );
}
