// th/components/events/event-details.vue
<script setup lang="ts">
const eid = useRouteParams<string>("eid")
const year = useRouteParams<string>("year")
const paramName = useRouteParams<string>("name")
const name = computed(() => decodeName(paramName.value))

// API call
const { data: event, status } = await useFetch<EventDetailsType>("/api/event-details", { query: { eid } })

const eventDetails = computed(() => {
  if (event.value) {
    return [
      { id: "name", title: "Sponsor Name", value: event.value.ename ?? "—" },
      { id: "category", title: "Category", value: event.value.category ?? "—" },
      { id: "dates", title: "Dates", value: event.value.dates },
      { id: "surface", title: "Surface", value: event.value.surface },
      { id: "venues", title: event.value.venues.length === 1 ? "Venue" : "Venues", value: event.value.venues },
      { id: "supervisors", title: event.value.supervisors.length === 1 ? "Supervisor" : "Supervisors", value: event.value.supervisors },
      { id: "pm", title: "Prize Money", value: event.value.currency && event.value.pm ? `${CURRENCIES[event.value.currency]}${event.value.pm}` : "—" },
      { id: "tfc", title: "Total Financial Commitment", value: event.value.currency && event.value.tfc ? `${CURRENCIES[event.value.currency]}${event.value.tfc}` : "—" }
    ]
  }
})
</script>

<template>
  <u-page-grid v-if="event">
    <details-card
      v-for="detail in eventDetails"
      :key="detail.id"
      :detail
    />
  </u-page-grid>
  <u-page-grid v-else-if="status === 'pending'">
    <details-loading-card
      v-for="_ in 10"
      :key="_"
    />
  </u-page-grid>
  <error-message
    v-else
    :title="`No details found for ${name} ${year}`"
    :status
    :error="`Error fetching details for ${name} ${year}`"
  />
</template>

// client2/src/components/Event/EventDetails.jsx
import { Card, Col, Descriptions, Row, Statistic } from "antd";
import { formattedDates } from "../../utils/utils";
import { CURRENCIES, SURFACES } from "../../utils/variables";

export default function EventDetails({ event }) {
  const statistics = [
    { title: "Prize Money", value: event.pm || "—" },
    { title: "Total Financial Commitment", value: event.tfc || "—" },
  ];

  const details = [
    { label: "Sponsor name", text: event.sponsor_name ?? "—" },
    { label: "Category", text: event.category ?? "—" },
    { label: "Dates", text: formattedDates(event.start_date, event.end_date) },
    {
      label: "Surface",
      text: SURFACES[event.surface.id] ?? "—",
    },
    {
      label: "Venue",
      text: event.venue ? (
        <div className="flex flex-col justify-center">
          <div>{event.venue.name || "—"}</div>
          <div>
            {event.venue.city}, {event.venue.country.name}
          </div>
        </div>
      ) : (
        "—"
      ),
    },
    {
      label: event.supervisors.length === 1 ? "Supervisor" : "Supervisors",
      text:
        event.supervisors.length > 0
          ? event.supervisors.map((supervisor) => (
              <div key={supervisor.id}>{supervisor.id}</div>
            ))
          : "—",
    },
  ];

  return (
    <>
      <Row justify="space-evenly">
        {statistics.map((stat) => {
          return (
            <Col span={6} key={stat.title}>
              <Card>
                <Statistic
                  title={stat.title}
                  value={stat.value}
                  prefix={CURRENCIES[event.currency] || ""}
                  className="text-center"
                />
              </Card>
            </Col>
          );
        })}
      </Row>
      <Descriptions
        colon={false}
        className="my-10"
        bordered
        layout="vertical"
        size="middle"
      >
        {details.map((detail) => {
          return (
            <Descriptions.Item key={detail.label} label={detail.label}>
              {detail.text}
            </Descriptions.Item>
          );
        })}
      </Descriptions>
    </>
  );
}
