// components/Edition/ResultCard.vue
<script setup lang="ts">
import { useDisplay } from 'vuetify';
import * as functions from '../utils';
import type { MatchResult, Status } from '../interfaces';

const props = defineProps<{
    match: MatchResult
    seeds: string[]
    statuses: Status
}>()

const { xl } = useDisplay()

const findStatus = (value: string): keyof Status | string => {
    for (const key in props.statuses) {
        if (props.statuses[key as keyof Status].includes(value)) {
            return key as keyof Status
        }
    }
    return ''
}
</script>

<template>
    <short-card class="my-5 mx-2 text-zinc-300 text-xs sm:w-1/2 lg:w-2/5">
        <v-container>
            <v-row>
                <v-col>
                    <span v-if="match.date">{{ functions.formatDate(match.date) }}</span>
                    <span v-if="match.date && match.court"> — </span>
                    <span v-if="match.court">{{ match.court }}</span>
                </v-col>
                <v-col
                    v-if="match.duration"
                    class="text-right"
                    cols="3"
                >
                    {{ functions.formatTime(match.duration) }}
                </v-col>
            </v-row>
            <v-row dense class="py-2">
                <v-col
                    class="flex items-center"
                    :cols="match.loser_score?.incomplete ? 5 : 8"
                >
                    <div class="mx-0.5">
                        <flag-img
                            class="w-[1rem] lg:w-[2rem]"
                            :src="functions.flagSrc(match.winner.country.id)"
                            :alt="match.winner.country.name"
                        />
                    </div>
                    <div class="mx-0.5">
                        <v-avatar :size="xl ? 'small' : 'x-small'">
                            <v-img
                                :src="functions.headshot(match.winner.id)"
                                :alt="match.winner.full_name"
                            />
                        </v-avatar>
                    </div>
                    <div class="mx-0.5">
                        <router-link
                            class="hover-link"
                            :to="{name: 'Player', params: {name: functions.encodeName(match.winner.full_name), id: match.winner.id}}"
                        >
                            {{ match.winner.full_name }}
                        </router-link>
                        
                        <small
                           v-if="seeds.includes(match.winner.id) || Object.values(statuses).some(array => array.includes(match.winner.id))"
                            class="text-[8px] xl:text-[10px]"
                        >
                             ({{ seeds.indexOf(match.winner.id) + 1 || '' }}{{ findStatus(match.winner.id) }})
                        </small>
                    </div>
                </v-col>
                <v-col
                    class="flex items-center"
                    cols="1"
                >
                    <v-icon
                        class="text-green-500 text-xs"
                        icon="fad fa-check"
                    />
                </v-col>
                <v-col
                    class="flex flex-row-reverse items-center"
                    cols="3"
                >
                    <div class="flex">
                        <div>{{ match.winner_score?.s1 }}<sup>{{ match.winner_score?.t1 }}</sup></div>
                        &nbsp;<div>{{ match.winner_score?.s2 }}<sup>{{ match.winner_score?.t2 }}</sup></div>
                        &nbsp;<div>{{ match.winner_score?.s3 }}<sup>{{ match.winner_score?.t3 }}</sup></div>
                        &nbsp;<div>{{ match.winner_score?.s4 }}<sup>{{ match.winner_score?.t4 }}</sup></div>
                        &nbsp;<div>{{ match.winner_score?.s5 }}<sup>{{ match.winner_score?.t5 }}</sup></div>
                    </div>
                </v-col>
                <v-col 
                    v-if="match.loser_score?.incomplete"
                    cols="2"
                />
            </v-row>
            <v-row dense>
                <v-col
                    v-if="match.loser"
                    class="flex items-center"
                    :cols="match.loser_score?.incomplete ? 5 : 8"
                >
                    <div class="mx-0.5">
                        <flag-img
                            class="w-[1rem] lg:w-[2rem]"
                            :src="functions.flagSrc(match.loser.country.id)"
                            :alt="match.loser.country.name"
                        />
                    </div>
                    <div class="mx-0.5">
                        <v-avatar :size="xl ? 'small' : 'x-small'">
                            <v-img
                                :src="functions.headshot(match.loser.id)"
                                :alt="match.loser.full_name"
                            />
                        </v-avatar>
                    </div>
                    <div class="mx-0.5">
                        <router-link
                            class="hover-link"
                            :to="{name: 'Player', params: {name: functions.encodeName(match.loser.full_name), id: match.loser.id}}"
                        >
                            {{ match.loser.full_name }}
                        </router-link>
                        <small
                           v-if="seeds.includes(match.loser.id) || Object.values(statuses).some(array => array.includes(match.loser?.id))"
                            class="text-[8px] xl:text-[10px]"
                        >
                             ({{ seeds.indexOf(match.loser.id) + 1 || '' }}{{ findStatus(match.loser.id) }})
                        </small>
                    </div>
                </v-col>
                <v-col v-else>BYE</v-col>
                <v-col cols="1"></v-col>
                <v-col
                    class="flex flex-row-reverse items-center"
                    cols="3"
                >
                    <div class="flex">
                        <div>{{ match.loser_score?.s1 }}<sup>{{ match.loser_score?.t1 }}</sup></div>
                        &nbsp;<div>{{ match.loser_score?.s2 }}<sup>{{ match.loser_score?.t2 }}</sup></div>
                        &nbsp;<div>{{ match.loser_score?.s3 }}<sup>{{ match.loser_score?.t3 }}</sup></div>
                        &nbsp;<div>{{ match.loser_score?.s4 }}<sup>{{ match.loser_score?.t4 }}</sup></div>
                        &nbsp;<div>{{ match.loser_score?.s5 }}<sup>{{ match.loser_score?.t5 }}</sup></div>
                    </div>
                </v-col>
                <v-col
                    v-if="match.loser_score?.incomplete"
                    class="flex items-center justify-center"
                    cols="2"
                >
                    {{ match.loser_score.incomplete }}.
                </v-col>
            </v-row>
            <v-row v-if="match.loser">
                <v-col>{{ match.umpire ?? '' }}</v-col>
                <v-col class="flex justify-end">
                    <v-chip
                        v-if="!match.incomplete"
                        class="mx-1"
                        :to="{name: 'H2H', params: {p1Name: functions.encodeName(match.winner.full_name), p1Id: match.winner.id, p2Name: functions.encodeName(match.loser.full_name), p2Id: match.loser.id}}"
                        :size="xl ? 'small' : 'x-small'"
                    >
                        H2H
                    </v-chip>
                    <v-chip
                        v-if="!match.incomplete && match.loser_score?.incomplete !== 'WO'"
                        class="mx-1"
                        :to="{name: 'MatchStats', params: {matchId: match.match_no}}"
                        :size="xl ? 'small' : 'x-small'"
                    >
                        Stats
                    </v-chip>
                </v-col>
            </v-row>
        </v-container>
    </short-card>
</template>

// client2/src/components/Event/ResultCard.jsx
import { Avatar, Card, Col, Image, Row, Tag } from "antd";
import { CheckCircleTwoTone } from "@ant-design/icons";
import { encodeName, formatDate, formatTime } from "../../utils/utils";
import { useParams } from "react-router";
import { Link } from "react-router-dom";
import PlayerItem from "../Global/PlayerItem";
import ScoreItem from "../Global/ScoreItem";

export default function ResultCard({ match }) {
  const { tname, tid, year, eid } = useParams();

  const title = (
    <div>
      {match.date ? <div>{formatDate(match.date)}</div> : null}
      {match.court && <div>{match.court}</div>}
    </div>
  );

  const extra = (
    <div>
      {match.duration_mins ? (
        <div className="text-right">{formatTime(match.duration_mins)}</div>
      ) : null}
      {match.umpire && <div className="text-right">{match.umpire.id}</div>}
    </div>
  );

  const entryInfo = (entry) => {
    if (entry.seed && entry.status) {
      return `(${entry.seed} ${entry.status})`;
    } else if (entry.seed) {
      return `(${entry.seed})`;
    } else if (entry.status) {
      return `(${entry.status})`;
    }
  };

  const actions = [
    !match.incomplete && (
      <Tag className="mx-auto bg-transparent border-zinc-300">
        <Link
          to={`/tournaments/${tname}/${tid}/${year}/${eid}/${match.match_no}`}
          className="!text-zinc-300"
        >
          Stats
        </Link>
      </Tag>
    ),
    match.incomplete !== "B" && (
      <Tag className="mx-auto bg-transparent border-zinc-300">
        <Link
          to={`/h2h/${encodeName(match.winner.player.player.full_name)}/${
            match.winner.player.player.id
          }/${encodeName(match.loser.player.player.full_name)}/${
            match.loser.player.player.id
          }`}
          className="!text-zinc-300"
        >
          H2H
        </Link>
      </Tag>
    ),
  ];

  return (
    <>
      <Card
        title={title}
        extra={extra}
        actions={actions}
        className="h-full flex flex-col justify-between p-1"
      >
        <Row className="mb-2">
          <Col span={19}>
            <Row className="items-center">
              <PlayerItem
                player={match.winner.player.player}
                entry={entryInfo(match.winner.player)}
              />
            </Row>
          </Col>
          <Col span={2}>
            <CheckCircleTwoTone twoToneColor="#52c41a" />
          </Col>
          <Col className="flex" span={3}>
            <ScoreItem score={match.winner} />
          </Col>
        </Row>
        <Row className="mt-2">
          <Col span={19}>
            <Row className="items-center">
              {match.loser ? (
                <PlayerItem
                  player={match.loser.player.player}
                  entry={entryInfo(match.loser.player)}
                />
              ) : (
                <>
                  <Col span={6} />
                  <Col span={18}>BYE</Col>
                </>
              )}
            </Row>
          </Col>
          <Col span={2}>
            {match.loser?.incomplete && (
              <Tag color="#f5222d">{match.loser.incomplete}</Tag>
            )}
          </Col>
          <Col className="flex" span={3}>
            {match.loser && <ScoreItem score={match.loser} />}
          </Col>
        </Row>
      </Card>
    </>
  );
}
