// client/src/App.jsx
import "./App.css";
import { Layout, ConfigProvider, theme } from "antd";
import Head from "./components/Header/Header";
import Foot from "./components/Footer/Footer";
import Main from "./components/Main";

const { Header, Content, Footer } = Layout;

function App() {
  return (
    <ConfigProvider
      theme={{
        algorithm: theme.darkAlgorithm,
        token: {
          colorPrimary: "#8b5cf6",
          colorTextTertiary: "#a1a1aa",
        },
        components: {
          Select: {
            activeBorderColor: "#8b5cf6",
            hoverBorderColor: "#8b5cf6",
            colorBorder: "#8b5cf6",
            colorText: "#d4d4d8",
          },
          Card: {
            colorBgContainer: "#5b21b6",
          },
          Descriptions: {
            labelBg: "#5b21b6",
          },
          Table: {
            headerBg: "#5b21b6",
          },
          Progress: {
            circleTextFontSize: "1rem",
          },
          Button: {
            contentFontSizeSM: 12,
            linkHoverBg: "#a1a1aa",
          },
        },
      }}
    >
      <Layout className="font-fira">
        <Header
          style={{
            position: "sticky",
            top: 0,
            zIndex: 999,
            width: "100%",
            display: "flex",
            alignItems: "center",
          }}
          className="bg-violet-800"
        >
          <Head />
        </Header>
        <Content className="py-16 w-[75%] mx-auto">
          <Main />
        </Content>
        <Footer className="bg-violet-800">
          <Foot />
        </Footer>
      </Layout>
    </ConfigProvider>
  );
}

export default App;

// client/src/App.vue
<script setup>
import { RouterView } from 'vue-router'
import { theme } from 'ant-design-vue'
import { COLOURS } from './utils/variables';

// [GLOBAL: ADD RESPONSIVE DESIGN]
// [FUTURE: CONVERT TO TYPESCRIPT?]

const tokenColours = { colorPrimary: COLOURS.violet800 }
const componentThemes = {
  Card: { colorBgContainer: COLOURS.violet800 },
  Select: {
    activeBorderColor: COLOURS.violet800,
    hoverBorderColor: COLOURS.violet800,
    colorBorder: COLOURS.violet800,
    colorText: COLOURS.zinc300,
  },
  Anchor: { colorPrimary: COLOURS.violet700 }
}
</script>

<template>
  <a-style-provider hash-priority="low">
    <a-config-provider :theme="{
      algorithm: theme.darkAlgorithm,
      token: tokenColours,
      components: componentThemes
    }">
      <a-layout class="flex flex-col min-h-screen">
        <a-layout-header class="!bg-violet-800 sticky top-0 z-50 w-full flex items-center">
          <Header class="" />
        </a-layout-header>
        <a-layout-content class="flex-1 py-16 w-3/4 mx-auto font">
          <RouterView :key="$route.fullPath" />
          <a-back-top type="primary" />
        </a-layout-content>
        <a-layout-footer class="!bg-violet-800">
          <Footer />
        </a-layout-footer>
      </a-layout>
    </a-config-provider>
  </a-style-provider>
</template>

<style>
.font,
div {
  font-family: 'Fira Sans', sans-serif
}
</style>
