// client2/src/components/Global/EventCard.jsx
import { Link } from "react-router-dom";
import { DateTime } from "luxon";
import { Card, Row, Col, Image, Button, Tooltip } from "antd";
import { encodeName, formattedDates } from "../../utils/utils";
import { SURFACES } from "../../utils/variables";

export default function EventCard({ event }) {
  const { Meta } = Card;

  const eventPages = [
    { name: "Details", slug: "" },
    { name: "Results", slug: "results" },
    { name: "Draw", slug: "draw" },
  ];

  const eventButton = (page) => {
    const isDisabled = DateTime.now() < DateTime.fromISO(event.start_date);

    const button = (
      <Button
        type="dashed"
        ghost={true}
        shape="round"
        size="small"
        block={true}
        disabled={isDisabled}
        className="!w-11/12 custom-disabled !text-zinc-300 !border-zinc-300 hover:!text-zinc-400 hover:!border-zinc-400"
        key={page.name}
        href={`/tournaments/${encodeName(event.tournament.name)}/${
          event.tournament.id
        }/${event.year.id}/${event.id}/${page.slug}`}
      >
        {page.name}
      </Button>
    );

    return isDisabled ? (
      <Tooltip title="Event has not started yet">{button}</Tooltip>
    ) : (
      button
    );
  };

  const eventButtons = eventPages.map((page) => {
    return eventButton(page);
  });

  return (
    <Card
      cover={
        <img
          alt={event.venue?.country.name || event.category}
          src={
            event.venue
              ? `./flags/${event.venue.country.id}.svg`
              : `./category/${event.category}.svg`
          }
          className="h-48 object-cover opacity-75 -z-10"
        />
      }
      actions={eventButtons}
      className="h-full flex flex-col justify-between"
    >
      <Row>
        <Col span={24}>
          <Meta
            title={
              <Link
                to={`/tournaments/${event.tournament.name}/${event.tournament.id}`}
                className="hover-link text-wrap"
              >
                {event.tournament.name}
              </Link>
            }
            description={event.sponsor_name ?? ""}
          />
        </Col>
        <Col span={19}>
          <div className="mt-3 flex flex-col justify-center">
            {event.venue && (
              <div>
                {event.venue.city}, {event.venue.country.name}
              </div>
            )}
            <div>{formattedDates(event.start_date, event.end_date)}</div>
            {event.surface && <div>{SURFACES[event.surface.id]}</div>}
          </div>
        </Col>
        <Col span={5} className="self-center">
          {event.category && (
            <Image
              alt={event.category}
              src={`/category/${event.category}.svg`}
            />
          )}
        </Col>
      </Row>
    </Card>
  );
}

// tennishistory/components/event-card.vue
<script setup lang="ts">
const props = defineProps<{ event: EventCardType }>();
const { surface, country, city, tname, tid, ename, year, eid, start, dates, category } = props.event;

// Disabled buttons if event has not started yet
const startDate = new Date(start);
const currentDate = new Date();
const isDisabled = currentDate < startDate;

// Get country code for icons
const countryCode = getCountryCode(country);

// Route params
const tournamentName = computed(() => encodeName(tname));
</script>

<template>
	<shadcn-card
		class="full-card"
		:id="eid"
	>
		<shadcn-card-header>
			<shadcn-card-title class="flex items-center gap-3">
				<div>
					<shadcn-avatar class="border border-zinc-400/50">
						<shadcn-avatar-image
							:src="`/category/${category}.svg`"
							:alt="category"
							class="bg-gray-100/50 dark:bg-surface-400/50"
						/>
						<shadcn-avatar-fallback>
							<Icon name="game-icons:tennis-court" />
						</shadcn-avatar-fallback>
					</shadcn-avatar>
				</div>
				<div>
					<nuxt-link
						class="hover-link"
						:to="{ name: 'tournament', params: { tname: tournamentName, tid } }"
					>
						{{ tname }}
					</nuxt-link>
				</div>
			</shadcn-card-title>
			<shadcn-card-description>
				<div v-if="ename">{{ ename }}</div>
			</shadcn-card-description>
		</shadcn-card-header>
		<shadcn-card-content>
			<shadcn-separator class="mt-2 mb-4" />
			<div class="flex flex-col gap-1 justify-end text-zinc-500 dark:text-zinc-400 text-sm">
				<div
					v-if="city"
					class="text-center md:text-left flex items-center gap-2"
				>
					<span>{{ city }}</span>
					<span>
						<flag-icon :country />
					</span>
				</div>
				<div class="text-center md:text-left">{{ dates }}</div>
				<div
					v-if="surface"
					class="text-center md:text-left"
				>
					{{ surface }}
				</div>
			</div>
		</shadcn-card-content>
		<shadcn-card-footer class="flex flex-wrap justify-center md:justify-evenly mt-5 gap-2 lg:gap-1">
			<template
				v-for="page in EVENT_PAGES"
				:key="page.title"
			>
				<div
					v-if="isDisabled"
					v-tooltip="'Event has not started yet'"
				>
					<shadcn-button
						v-tooltip="'Event has not started yet'"
						disabled
						size="xs"
						class="rounded-full"
					>
						<div class="text-zinc-400 cursor-not-allowed">
							<icon :name="page.icon" />
							{{ page.title }}
						</div>
					</shadcn-button>
				</div>
				<shadcn-button
					v-else
					size="xs"
					class="rounded-full"
					as-child
				>
					<div>
						<Icon :name="page.icon" />
						<nuxt-link
							:to="`/tournaments/${tournamentName}/${tid}/${year}/${eid}/${page.route}`"
							class="hover-link"
						>
							{{ page.title }}
						</nuxt-link>
					</div>
				</shadcn-button>
			</template>
		</shadcn-card-footer>
	</shadcn-card>
</template>
