// client2/src/components/Tournament/TournamentBreadcrumbs.jsx
import { Breadcrumb } from "antd";

export default function TournamentBreadcrumbs({ name, events }) {
  const getYears = (event) => {
    return {
      path: `/${event.year.id}/${event.id}`,
      title: event.year.id,
    };
  };
  const breadcrumbs = [
    {
      title: "Home",
      key: "1",
      href: "/",
    },
    {
      title: name,
      key: "2",
      menu: {
        items: events.map(getYears).reverse(),
      },
    },
  ];
  return <Breadcrumb items={breadcrumbs} />;
}

// client/src/components/Tournament/TournamentBreadcrumbs.vue
<script setup>
import { encodeName } from '@/utils/functions';

const props = defineProps(['tournament'])
</script>

<template>
    <a-breadcrumb separator=">">
        <a-breadcrumb-item>
            <router-link :to="{ name: 'home' }">Home</router-link>
        </a-breadcrumb-item>
        <a-breadcrumb-item>
            {{ tournament.name }}
            <template #overlay>
                <a-menu>
                    <a-menu-item v-for="event in tournament.events" :key="event.id">
                        <router-link
                            :to="{ name: 'event', params: { id: tournament.id, name: encodeName(tournament.name), year: event.year.id, eid: event.id } }">{{
                                event.year.id }}</router-link>
                    </a-menu-item>
                </a-menu>
            </template>
        </a-breadcrumb-item>
    </a-breadcrumb>
</template>
