// client/src/components/Tournament/TournamentCard.jsx
import { Card, Col, Row } from "antd";
import { Link } from "react-router-dom";
import PlayerItem from "../Global/PlayerItem";
import WinnerScore from "../Global/WinnerScore";

export default function TournamentCard({ event }) {
  const { Meta } = Card;

  if (event.rounds.length > 0) {
    const final = event.rounds[0]?.matches[0];

    const players = (
      <div>
        <Row className="items-center mb-2">
          <PlayerItem player={final.winner.player.player} />
        </Row>
        <Row className="justify-center">
          <Col>d.</Col>
        </Row>
        <Row className="mt-2 items-center">
          <PlayerItem player={final.loser.player.player} />
        </Row>
      </div>
    );

    return (
      <>
        <Card
          title={
            <Link className="hover-link" to={`${event.year.id}/${event.id}`}>
              {event.year.id}
            </Link>
          }
        >
          <Meta
            title={players}
            description={
              <WinnerScore winner={final.winner} loser={final.loser} />
            }
            className="text-center"
          />
        </Card>
      </>
    );
  }
}

// client/src/components/Tournament/TournamentCard.vue
<script setup>
const props = defineProps(['event', 'id', 'name'])
const final = props.event.rounds[0].matches[0]
const eventParams = {
    name: props.name,
    id: props.id,
    year: props.event.year.id,
    eid: props.event.id
}
const matchParams = { ...eventParams, mid: final.match_no }
</script>

<template>
    <a-card>
        <template #title>
            <router-link class="hover-link" :to="{ name: 'event', params: eventParams }">{{
                event.year.id }}</router-link>
        </template>
        <a-card-meta class="text-center">
            <template #title>
                <PlayerRow :player="final.winner.player.player" class="items-center mb-2" />
                <a-row class="justify-center">d.</a-row>
                <PlayerRow :player="final.loser.player.player" class="items-center mt-2" />
            </template>
            <template #description>
                <router-link :to="{ name: 'match', params: matchParams }">
                    <WinnerScore :winner="final.winner" :loser="final.loser" />
                </router-link>
            </template>
        </a-card-meta>
    </a-card>
</template>
