// client/src/components/Global/TournamentBreadcrumbs.jsx
import { useMatch, useParams } from "react-router";
import { Link } from "react-router-dom";
import { useQuery } from "@apollo/client";
import { Breadcrumb } from "antd";
import { unencodeName } from "../../utils/utils";
import { GET_TOURNAMENT_YEARS } from "../../services/TournamentService";

export default function TournamentBreadcrumbs() {
  const { tname, tid, year, eid, mid } = useParams();
  const eventOverview = useMatch("/tournaments/:tname/:tid/:year/:eid");
  const eventResults = useMatch("/tournaments/:tname/:tid/:year/:eid/results");
  const eventDraw = useMatch("/tournaments/:tname/:tid/:year/:eid/draw");
  const matchPage = useMatch("/tournaments/:tname/:tid/:year/:eid/:mid");

  const { loading, error, data } = useQuery(GET_TOURNAMENT_YEARS, {
    variables: { id: parseInt(tid) },
  });
  if (error) console.error(error);

  const breadcrumbs = [
    {
      title: <Link to={"/"}>Home</Link>,
      key: "home",
    },
    {
      title: (
        <Link to={`/tournaments/${tname}/${tid}`}>{unencodeName(tname)}</Link>
      ),
      key: "tournament",
      ...(data && {
        menu: {
          items: data.tournaments[0].events
            .map((event) =>
              parseInt(year) === event.year.id
                ? null
                : {
                    key: `event-${event.year.id}`,
                    title: (
                      <Link
                        to={`/tournaments/${tname}/${tid}/${event.year.id}/${event.id}`}
                      >
                        {event.year.id}
                      </Link>
                    ),
                  }
            )
            .filter(Boolean),
        },
      }),
    },
    year && {
      title: year,
      key: "event",
      menu: {
        items: [
          eventOverview
            ? null
            : {
                title: (
                  <Link to={`/tournaments/${tname}/${tid}/${year}/${eid}`}>
                    Details
                  </Link>
                ),
                key: `details-${eid}`,
              },
          eventResults
            ? null
            : {
                title: (
                  <Link
                    to={`/tournaments/${tname}/${tid}/${year}/${eid}/results`}
                  >
                    Results
                  </Link>
                ),
                key: `results-${eid}`,
              },
          eventDraw
            ? null
            : {
                title: (
                  <Link to={`/tournaments/${tname}/${tid}/${year}/${eid}/draw`}>
                    Draw
                  </Link>
                ),
                key: `draw-${eid}`,
              },
        ].filter(Boolean),
      },
    },
    mid && {
      title: mid,
      key: mid,
    },
  ].filter(Boolean);
  return <Breadcrumb items={breadcrumbs} />;
}

// client/src/components/Tournament/TournamentBreadcrumbs.vue
<script setup>
import { ref, watch } from 'vue';
import { useRoute } from 'vue-router';
import { useQuery } from '@vue/apollo-composable';
import { GET_TOURNAMENT_YEARS } from '@/services/TournamentService';
import { GET_MATCH_BREADCRUMBS } from '@/services/MatchService';
import { unencodeName } from '@/utils/functions';

const route = useRoute()
const tournamentYears = ref(null)
const rounds = ref(null)
const match = ref(null)
const pages = [{ name: 'event', title: 'Details' }, { name: 'results', title: 'Results' }, { name: 'draw', title: 'Draw' }]
const open = ref(false)
const selectedRound = ref(null)

const showDrawer = (round) => {
    open.value = true
    selectedRound.value = round
}

if (route.name !== 'match') {
    const { query, variables } = GET_TOURNAMENT_YEARS(parseInt(route.params.id))
    const { result, loading, error } = useQuery(query, variables)

    watch(result, (newResult) => {
        if (newResult) tournamentYears.value = newResult.tournaments[0].events
    })

    watch(error, newError => {
        if (newError) console.error(newError)
    })
} else {
    const { query, variables } = GET_MATCH_BREADCRUMBS(parseInt(route.params.id), parseInt(route.params.eid), parseInt(route.params.mid))
    const { result, loading, error } = useQuery(query, variables)
    watch(result, (newResult) => {
        if (newResult) {
            tournamentYears.value = newResult.tournaments[0].events
            rounds.value = newResult.events[0].rounds
            match.value = newResult.matches[0]
        }
    })

    watch(error, newError => {
        if (newError) console.error(newError)
    })
}
</script>

<template>
    <a-breadcrumb v-if="tournamentYears">
        <a-breadcrumb-item>
            <router-link :to="{ name: 'home' }">Home</router-link>
        </a-breadcrumb-item>
        <a-breadcrumb-item>
            {{ unencodeName(route.params.name) }}
            <template #overlay>
                <a-menu>
                    <template v-for="event in tournamentYears" :key="event.id">
                        <a-menu-item v-if="route.name === 'tournament' || parseInt(route.params.eid) !== event.id">
                            <router-link :to="{ name: 'event', params: { year: event.year.id, eid: event.id } }">{{
                                event.year.id }}</router-link>
                        </a-menu-item>
                    </template>
                </a-menu>
            </template>
        </a-breadcrumb-item>
        <a-breadcrumb-item v-if="route.name !== 'tournament'">
            {{ route.params.year }}
            <template #overlay>
                <a-menu>
                    <template v-for="page in pages" :key="page.name">
                        <a-menu-item v-if="route.name !== page.name">
                            <router-link :to="{ name: page.name }">{{ page.title }}</router-link>
                        </a-menu-item>
                    </template>
                </a-menu>
            </template>
        </a-breadcrumb-item>
        <a-breadcrumb-item v-if="route.name === 'match'">
            {{ match.round.round }}
            <template #overlay>
                <a-menu>
                    <template v-for="round in rounds" :key="round.round">
                        <a-menu-item v-if="match.round.round !== round.round" @click="showDrawer(round)">
                            {{ round.round }}
                        </a-menu-item>
                    </template>
                </a-menu>
            </template>
        </a-breadcrumb-item>
        <a-breadcrumb-item v-if="route.name === 'match'">
            {{ match.p1.player.player.full_name }} vs. {{ match.p2.player.player.full_name }}
            <template #overlay>
                <a-menu>
                    <template v-for="roundMatch in match.round.matches" :key="roundMatch.match_no">
                        <a-menu-item v-if="route.params.mid !== roundMatch.match_no">
                            <router-link :to="{ name: 'match', params: { mid: roundMatch.match_no } }">{{
                                roundMatch.p1.player.player.full_name }} vs. {{ roundMatch.p2.player.player.full_name
                                }}</router-link>
                        </a-menu-item>
                    </template>
                </a-menu>
            </template>
        </a-breadcrumb-item>
    </a-breadcrumb>
    <a-drawer v-if="selectedRound" v-model:open="open" :title="selectedRound.round" class="!bg-violet-800">
        <div v-for="roundsMatch in selectedRound.matches" :key="roundsMatch.match_no" class="my-1">
            <router-link class="hover-link" :to="{ name: 'match', params: { mid: roundsMatch.match_no } }">{{
                roundsMatch.p1.player.player.full_name }} vs. {{ roundsMatch.p2.player.player.full_name
                }}</router-link>
        </div>
    </a-drawer>
</template>
