// client/src/views/Home/Home.vue
<script setup lang="ts">
import { ref, watch, type Ref } from 'vue';
import apolloClient from '@/apollo';
import { provideApolloClient, useQuery } from '@vue/apollo-composable';
import { DateTime } from 'luxon';
import { getUpcomingEvents } from '@/services/EventService';
import type { Event } from '@/utils/interfaces';
import Title from '@/components/Global/Title.vue';
import Loading from '@/components/Global/Loading.vue';
import EventCard from '@/components/Global/EventCard.vue';

provideApolloClient(apolloClient)

const { query, variables } = getUpcomingEvents(DateTime.now().toISODate())
const { result, loading, error } = useQuery(query, variables)

const events: Ref<Event[]> = ref([])

watch(result, (newResult) => {
    if (newResult) events.value = newResult.events
}, { immediate: true })

watch(error, (newError) => {
    if (newError) console.error(newError)
})
</script>

<template>
    <v-sheet class="bg-transparent m-16 w-75 pa-3 mx-auto">
        <Title>
            <template #title>Upcoming Tournaments</template>
        </Title>
        <v-container v-if="events.length > 0">
            <v-row>
                <v-col v-for="event in events" :key="event.id" cols="12" sm="4" xl="3">
                    <EventCard :event />
                </v-col>
            </v-row>
        </v-container>
        <Loading v-else :loading>
            <template #none>No upcoming tournaments</template>
        </Loading>
    </v-sheet>
</template>

// client/src/components/Home/Home.jsx
import { useQuery } from "@apollo/client";
import { DateTime } from "luxon";
import { Col, Row } from "antd";
import { GET_UPCOMING } from "../../services/EventService";
import Title from "../Global/Title";
import Loading from "../Global/Loading";
import EventCard from "../Global/EventCard";

export default function Home() {
  const { loading, error, data } = useQuery(GET_UPCOMING, {
    variables: { date: DateTime.now().toISODate() },
  });
  if (error) console.error(error);

  return (
    <>
      <Title title="Upcoming Events" />
      {data && data.events.length > 0 && (
        <Row justify="space-evenly" align="stretch" gutter={[0, 32]}>
          {data.events.map((event) => {
            return (
              <Col xs={24} sm={11} md={7} xl={5} key={event.id}>
                <EventCard event={event} />
              </Col>
            );
          })}
        </Row>
      )}
      {(!data || data.events.length === 0) && (
        <Loading loading={loading} none="No upcoming events" />
      )}
    </>
  );
}
