// client/src/views/Event/Results.vue
<script setup lang="ts">
import { ref, watch, type Ref } from 'vue';
import apolloClient from '@/apollo';
import { provideApolloClient, useQuery } from '@vue/apollo-composable';
import { getResults } from '@/services/EventService';
import type { Match, EntryInfo } from '@/utils/interfaces';
import Loading from '@/components/Global/Loading.vue';
import ResultCard from '@/components/Event/ResultCard.vue';

provideApolloClient(apolloClient)

const props = defineProps<{
    eventId: string
}>()

const { query, variables } = getResults(parseInt(props.eventId))
const { result, loading, error } = useQuery(query, variables)

const rounds: Ref<{ round: string; matches: Match[] }[]> = ref([])
const entryInfo: Ref<{ node: { id: string }; properties: EntryInfo; }[]> = ref([])
const tab: Ref<string> = ref('')

watch(result, (newResult) => {
    if (newResult) {
        tab.value = newResult.events[0].draw_type
        entryInfo.value = newResult.events[0].playersConnection.edges
        rounds.value = newResult.events[0].rounds
    }
}, { immediate: true })

watch(error, (newError) => {
    if (newError) console.error(newError)
}, { immediate: true })
</script>

<template>
    <v-container v-if="rounds.length > 0">
        <v-tabs v-model="tab" show-arrows>
            <v-tab v-for="round in rounds" :key="round.round" :value="round.round">
                {{ round.round }}
            </v-tab>
        </v-tabs>
        <v-window v-model="tab" direction="vertical" class="mt-5">
            <v-window-item v-for="round in rounds" :key="round.round" :value="round.round">
                <div class="flex flex-wrap justify-center">
                    <ResultCard v-for="match in round.matches" :key="match.match_no" :match :entryInfo />
                </div>
            </v-window-item>
        </v-window>
    </v-container>
    <Loading v-else :loading>
        <template #None>No data available</template>
    </Loading>
</template>

// client/src/components/Event/Results.jsx
import { useParams } from "react-router";
import { Helmet } from "react-helmet-async";
import { useQuery } from "@apollo/client";
import { Anchor, Col, Row } from "antd";
import { unencodeName } from "../../utils/utils";
import { GET_RESULTS } from "../../services/EventService";
import Loading from "../Global/Loading";
import Title from "../Global/Title";
import ResultCard from "./ResultCard";

export default function Results() {
  const { tname, tid, year, eid } = useParams();

  const { loading, error, data } = useQuery(GET_RESULTS, {
    variables: { id: parseInt(eid) },
  });
  if (error) console.log(error);

  const getAnchors = (round) => {
    return {
      key: round.number,
      href: `#${round.round}`,
      title: round.round,
    };
  };

  return (
    <>
      <Helmet>
        <title>
          Results | {unencodeName(tname)} {year}
        </title>
      </Helmet>
      <Title title="Results" />
      {data && (
        <Row>
          <Col span={4}>
            <Anchor
              offsetTop={75}
              items={data.events[0].rounds.map(getAnchors)}
            />
          </Col>
          <Col span={20}>
            {data.events[0].rounds.map((round) => {
              return (
                <div key={round.number} id={round.round}>
                  <div className="text-4xl mb-5">{round.round}</div>
                  <Row justify="space-evenly" gutter={[0, 32]}>
                    {round.matches.map((match) => {
                      return (
                        <Col span={11} key={match.match_no}>
                          <ResultCard match={match} />
                        </Col>
                      );
                    })}
                  </Row>
                </div>
              );
            })}
          </Col>
        </Row>
      )}
      {!data && <Loading loading={loading} none="No data available" />}
    </>
  );
}
