// client/src/components/EventCard.vue
<script setup lang="ts">
import { DateTime } from 'luxon';
import type { Event } from '@/utils/interfaces';
import { flag, formattedDates, category, encodeName } from '@/utils/functions';

const props = defineProps<{
    event: Event
}>()
</script>

<template>
    <v-card class="my-4 sm:!my-5 !bg-indigo-800 mx-auto h-100 border-zinc-500" rounded="xl" variant="outlined">
        <v-img v-if="event.venue" class="align-end opacity-75" :src="flag(event.venue.country.id)"
            :alt="event.venue.country.name">
            <v-img v-if="event.category" class="!size-20 mx-2 my-1 bg-white rounded-circle"
                :src="category(event.category)" :alt="event.category" />
        </v-img>
        <v-card-title style="text-wrap: wrap;" class="text-center">
            <router-link v-if="event.tournament" class="hover-link"
                :to="{ name: 'Tournament', params: { name: encodeName(event.tournament.name), id: event.tournament.id } }">
                {{ event.tournament.name }}
            </router-link>
        </v-card-title>
        <v-card-subtitle v-if="event.sponsor_name" style="text-wrap: wrap;" class="small text-center">
            {{ event.sponsor_name }}
        </v-card-subtitle>
        <v-card-text v-if="event.start_date && event.venue && event.surface" class="mt-1 text-zinc-300 text-center"
            style="text-wrap: wrap;">
            <div>{{ formattedDates(event.start_date, event.end_date) }}</div>
            <div>{{ event.venue.city }}, {{ event.venue.country.name }}</div>
            <div>
                {{ event.surface.environment }} {{ event.surface.surface }}
                <span v-if="event.surface.hard_type">
                    ({{ event.surface.hard_type }})
                </span>
            </div>
        </v-card-text>
        <v-card-actions v-if="DateTime.now() > DateTime.fromISO(event.start_date)">
            <v-chip v-if="event.tournament" class="mx-auto text-zinc-300" variant="outlined"
                :to="{ name: 'Event', params: { name: encodeName(event.tournament.name), id: event.tournament.id, year: event.year.id, eventId: event.id } }">
                Results
            </v-chip>
        </v-card-actions>
    </v-card>
</template>

// client2/src/components/Global/EventCard.jsx
import { Card, Row, Col, Image, Button } from "antd";
import { DateTime } from "luxon";
import { encodeName, formattedDates } from "../../utils/utils";
import { Link } from "react-router-dom";

export default function EventCard({ event }) {
  const { Meta } = Card;

  const eventPages = [
    <Button
      type="dashed"
      ghost={true}
      shape="round"
      size="small"
      disabled={DateTime.now() < DateTime.fromISO(event.start_date) && true}
      className="!w-2/3 custom-disabled !text-zinc-300 !border-zinc-300 hover:!text-zinc-400 hover:!border-zinc-400"
      href={`/tournaments/${encodeName(event.tournament.name)}/${
        event.tournament.id
      }/${event.year.id}/${event.id}`}
    >
      Details
    </Button>,
    <Button
      type="dashed"
      ghost={true}
      shape="round"
      size="small"
      disabled={DateTime.now() < DateTime.fromISO(event.start_date) && true}
      className="!w-2/3 custom-disabled !text-zinc-300 !border-zinc-300 hover:!text-zinc-400 hover:!border-zinc-400"
      href={`/tournaments/${encodeName(event.tournament.name)}/${
        event.tournament.id
      }/${event.year.id}/${event.id}/results`}
    >
      Results
    </Button>,
    <Button
      type="dashed"
      ghost={true}
      shape="round"
      size="small"
      disabled={DateTime.now() < DateTime.fromISO(event.start_date) && true}
      className="!w-2/3 custom-disabled !text-zinc-300 !border-zinc-300 hover:!text-zinc-400 hover:!border-zinc-400"
      href={`/tournaments/${encodeName(event.tournament.name)}/${
        event.tournament.id
      }/${event.year.id}/${event.id}/draw`}
    >
      Draw
    </Button>,
  ];

  if (event.venue && event.surface?.environment) {
    return (
      <Card
        cover={
          <img
            alt={event.venue.country.name}
            src={`./flags/${event.venue.country.id}.svg`}
            className="h-48 object-cover opacity-75 -z-10"
          />
        }
        actions={eventPages}
        className="h-full flex flex-col justify-between"
      >
        <Row>
          <Col span={19}>
            <Meta
              title={
                <Link
                  to={`/tournaments/${event.tournament.name}/${event.tournament.id}`}
                  className="hover-link"
                >
                  {event.tournament.name}
                </Link>
              }
              description={event.sponsor_name ?? ""}
            />
            <div className="mt-3 flex flex-col justify-center">
              <div>
                {event.venue.city}, {event.venue.country.name}
              </div>
              <div>{formattedDates(event.start_date, event.end_date)}</div>
              <div>
                {event.surface.environment} {event.surface.surface}
                {event.surface.hard_type ? (
                  <span> ({event.surface.hard_type})</span>
                ) : null}
              </div>
            </div>
          </Col>
          <Col span={5} className="self-center">
            <Image
              alt={event.category}
              src={`/category/${event.category}.svg`}
            />
          </Col>
        </Row>
      </Card>
    );
  }
}
