// client/src/components/Global/ScoreItem.vue
<script setup lang="ts">
const props = defineProps(['score'])
const scoreArray = Array.from({ length: 5 }, (_, i) => i + 1)
</script>

<template>
  <div class="flex justify-end w-full">
    <div v-for="set in scoreArray" class="mr-1">
      {{ score[`s${set}`] }}<sup>{{ score[`t${set}`] }}</sup>
    </div>
  </div>
</template>

// client2/src/components/Global/ScoreItem.jsx
export default function ScoreItem({ score }) {
  const scoreArray = Array.from({ length: 5 }, (_, i) => i);

  return (
    <>
      {scoreArray.map((set) => {
        return (
          <div key={set} className="mr-1">
            {score[`s${set + 1}`]}
            <sup>{score[`t${set + 1}`]}</sup>
          </div>
        );
      })}
    </>
  );
}
