// client2/src/components/Match/MatchStats.jsx
import { useParams } from "react-router";
import { Link } from "react-router-dom";
import { Helmet } from "react-helmet-async";
import { useQuery } from "@apollo/client";
import { Anchor, Avatar, Col, ConfigProvider, Image, Row } from "antd";
import { GET_MATCH_STATS } from "../../services/MatchStatService";
import { encodeName, unencodeName } from "../../utils/utils";
import Title from "../Global/Title";
import Loading from "../Global/Loading";
import MatchDetails from "./MatchDetails";
import ScoreBox from "./ScoreBox";
import ServiceStats from "./ServiceStats";
import ReturnStats from "./ReturnStats";
import PointStats from "./PointStats";
import ServeSpeed from "./ServeSpeed";

export default function MatchStats() {
  const { tname, tid, year, eid, mid } = useParams();
  const { loading, error, data } = useQuery(GET_MATCH_STATS, {
    variables: { matchNo: parseInt(mid), eventId: parseInt(eid) },
  });
  if (error) console.error(error);
  if (data) {
    const match = data.matches[0];
    const title = match.round.event.sponsor_name ?? unencodeName(tname);

    return (
      <>
        <Helmet>
          <title>
            {`${match.p1.player.player.full_name} v. ${match.p2.player.player.full_name}`}{" "}
            | TennisHistory
          </title>
        </Helmet>
        <Title title={title} />
        <Row>
          <Col span={4}>
            <Anchor
              offsetTop={75}
              items={[
                {
                  key: "1",
                  href: "#service-stats",
                  title: "Service Stats",
                },
                {
                  key: "2",
                  href: "#return-stats",
                  title: "Return Stats",
                },
                {
                  key: "3",
                  href: "#points-stats",
                  title: "Points Stats",
                },
                {
                  key: "4",
                  href: "#service-speed",
                  title: "Service Speed",
                },
              ]}
            />
          </Col>
          <Col span={20}>
            <MatchDetails match={match} />
            <ConfigProvider
              theme={{
                components: {
                  Card: {
                    colorBgContainer: "transparent",
                    headerBg: "#5b21b6",
                  },
                },
              }}
            >
              <Row align="middle">
                <Col
                  span={6}
                  className="text-center bg-violet-700 rounded-xl p-5"
                >
                  <Avatar
                    alt={match.p1.player.player.full_name}
                    src={`https://www.atptour.com/-/media/alias/player-headshot/${match.p1.player.player.id}`}
                    size={100}
                    className="border-zinc-300"
                  />
                  <Row className="my-5">
                    <Col span={4}>
                      <Image
                        alt={match.p1.player.player.country.name}
                        src={`/flags/${match.p1.player.player.country.id}.svg`}
                        className="rounded border-zinc-300 border-2"
                      />
                    </Col>
                    <Col span={19} className="text-xl pl-5">
                      <Link
                        className="hover-link"
                        to={`/players/${encodeName(
                          match.p1.player.player.full_name
                        )}/${match.p1.player.player.id}`}
                      >
                        {match.p1.player.player.full_name}
                      </Link>
                    </Col>
                  </Row>
                </Col>
                <Col span={12} className="px-16">
                  <ScoreBox
                    p1={match.p1}
                    p2={match.p2}
                    winner={match.winner.player.player.id}
                  />
                </Col>
                <Col
                  span={6}
                  className="text-center bg-emerald-800 rounded-xl p-5"
                >
                  <Avatar
                    alt={match.p2.player.player.full_name}
                    src={`https://www.atptour.com/-/media/alias/player-headshot/${match.p2.player.player.id}`}
                    size={100}
                    className="border-zinc-300"
                  />
                  <Row className="my-5">
                    <Col span={4}>
                      <Image
                        alt={match.p2.player.player.country.name}
                        src={`/flags/${match.p2.player.player.country.id}.svg`}
                        className="rounded border-zinc-300 border-2"
                      />
                    </Col>
                    <Col span={19} className="text-xl pl-5">
                      <Link
                        className="hover-link"
                        to={`/players/${encodeName(
                          match.p2.player.player.full_name
                        )}/${match.p2.player.player.id}`}
                      >
                        {match.p2.player.player.full_name}
                      </Link>
                    </Col>
                  </Row>
                </Col>
              </Row>

              <ServiceStats
                p1Aces={match.p1.aces}
                p2Aces={match.p2.aces}
                p1Dfs={match.p1.dfs}
                p2Dfs={match.p2.dfs}
                p1Serve1Win={match.p1.serve1_pts_w}
                p1Serve1={match.p1.serve1_pts}
                p1Serve2Win={match.p1.serve2_pts_w}
                p1Serve2={match.p1.serve2_pts}
                p2Serve1Win={match.p2.serve1_pts_w}
                p2Serve1={match.p2.serve1_pts}
                p2Serve2Win={match.p2.serve2_pts_w}
                p2Serve2={match.p2.serve2_pts}
                p1BpsSaved={match.p1.bps_saved}
                p1BpsFaced={match.p1.bps_faced}
                p2BpsSaved={match.p2.bps_saved}
                p2BpsFaced={match.p2.bps_faced}
              />

              <ReturnStats
                p1Ret1Win={match.p1.ret1_w}
                p1Ret1={match.p1.ret1}
                p2Ret1Win={match.p2.ret1_w}
                p2Ret1={match.p2.ret1}
                p1Ret2Win={match.p1.ret2_w}
                p1Ret2={match.p1.ret2}
                p2Ret2Win={match.p2.ret2_w}
                p2Ret2={match.p2.ret2}
                p1BpsConverted={match.p1.bps_converted}
                p1BpOpps={match.p1.bp_opps}
                p2BpsConverted={match.p2.bps_converted}
                p2BpOpps={match.p2.bp_opps}
              />

              <PointStats match={match} />
              {match.p1.max_speed_kph && (
                <ServeSpeed
                  p1Max={match.p1.max_speed_kph}
                  p1Avg1={match.p1.avg_sv1_kph}
                  p1Avg2={match.p1.avg_sv2_kph}
                  p2Max={match.p2.max_speed_kph}
                  p2Avg1={match.p2.avg_sv1_kph}
                  p2Avg2={match.p2.avg_sv2_kph}
                />
              )}
            </ConfigProvider>
          </Col>
        </Row>
      </>
    );
  }

  return (
    <>
      <Helmet>
        <title>{`${unencodeName(tname)} ${year} ${mid}`}</title>
      </Helmet>
      <Title title={`${unencodeName(tname)} ${year} ${mid}`} />
      <Loading loading={loading} none="No data available" />
    </>
  );
}

// client/src/views/Match/MatchStats.vue
<script setup lang="ts">
import { ref, type Ref, watch } from 'vue';
import apolloClient from '@/apollo';
import { provideApolloClient, useQuery } from '@vue/apollo-composable';
import { getMatchStats } from '@/services/MatchService';
import type { Match, EntryInfo } from '@/utils/interfaces';
import { unencodeName, formatDate, formattedDates, incomplete, encodeName, flag, headshot } from '@/utils/functions';
import Title from '@/components/Global/Title.vue';
import Loading from '@/components/Global/Loading.vue';
import ResultsBox from '@/components/MatchStats/ResultsBox.vue';
import DualStatItem from '@/components/MatchStats/DualStatItem.vue';
import ServiceStatItem from '@/components/MatchStats/ServiceStatItem.vue';
import StatItem from '@/components/MatchStats/StatItem.vue';

provideApolloClient(apolloClient)

const props = defineProps<{
    name: string,
    id: string,
    year: string,
    eventId: string,
    matchId: string
}>()

const { query, variables } = getMatchStats(parseInt(props.matchId), parseInt(props.eventId))
const { result, loading, error } = useQuery(query, variables)

const match: Ref<Match | null> = ref(null)
const entry1: Ref<{ node: { id: string }, properties: EntryInfo } | undefined> = ref()
const entry2: Ref<{ node: { id: string }, properties: EntryInfo } | undefined> = ref()

watch(result, (newResult) => {
    if (newResult) {
        match.value = newResult.matches[0]
        // @ts-ignore
        entry1.value = match.value?.round.event?.playersConnection?.edges.find(obj => obj.node.id === match.value?.p1?.player?.id)
        // @ts-ignore
        entry2.value = match.value?.round.event?.playersConnection?.edges.find(obj => obj.node.id === match.value?.p2?.player?.id)
    }
}, { immediate: true })

watch(error, (newError) => {
    if (newError) console.error(newError)
})

const updateDocumentTitle = () => {
    document.title = `${unencodeName(props.name)} ${props.year} ${props.matchId} | TennisHistory`
}

watch(() => props.name, () => {
    updateDocumentTitle()
}, { immediate: true })
</script>

<template>
    <v-sheet v-if="match" class="w-5/6 md:w-8/12 lg:w-1/2 mx-auto my-10 bg-transparent">
        <div class="text-zinc-300 text-center">
            <div class="text-3xl">
                <router-link class="hover-link" :to="{ name: 'Tournament' }">{{ match.round.event?.tournament?.name
                    }}</router-link>
            </div>
            <div class="text-xl">{{ match.round.event?.sponsor_name ?? '' }}</div>
            <div>{{ match.round.event?.surface?.environment }} {{ match.round.event?.surface?.surface }}<span
                    v-if="match.round.event?.surface?.hard_type"> ({{ match.round.event.surface.hard_type }})</span> |
                <span v-if="match.round.event?.start_date && match.round.event?.end_date">{{ match.date ?
                    formatDate(match.date) : formattedDates(match.round.event?.start_date, match.round.event?.end_date)
                    }}</span>
            </div>
        </div>
        <ResultsBox v-if="entry1 && entry2" :match :entry1="entry1.properties" :entry2="entry2.properties" />
        <v-container class="text-zinc-300" v-if="match.p1?.player && match.p2?.player">
            <v-row>
                <v-col class="text-center">
                    <v-avatar>
                        <v-img :src="headshot(match.p1.player.id)" :alt="match.p1.player.full_name" />
                    </v-avatar>
                    <div class="small mt-1 font-bold">
                        {{ match.p1.player.full_name }}
                    </div>
                </v-col>
                <v-col class="font-bold flex items-center justify-center">
                    SERVICE STATS
                </v-col>
                <v-col class="text-center">
                    <v-avatar>
                        <v-img :src="headshot(match.p2.player.id)" :alt="match.p2.player.full_name" />
                    </v-avatar>
                    <div class="small mt-1 font-bold">
                        {{ match.p2.player.full_name }}
                    </div>
                </v-col>
                <v-divider thickness="3" />
            </v-row>
            <StatItem v-if="match.p1.aces && match.p2.aces" :p1="match.p1.aces" :p2="match.p2.aces">
                <template #metric>Aces</template>
            </StatItem>
            <StatItem v-if="match.p1.dfs && match.p2.dfs" :p1="match.p1.dfs" :p2="match.p2.dfs" low>
                <template #metric>Double faults</template>
            </StatItem>
            <DualStatItem
                v-if="match.p1.serve1_pts && match.p1.serve2_pts && match.p2.serve1_pts && match.p2.serve2_pts"
                :p1Value="match.p1.serve1_pts" :p1Total="match.p1.serve1_pts + match.p1.serve2_pts"
                :p2Value="match.p2.serve1_pts" :p2Total="match.p2.serve1_pts + match.p2.serve2_pts">
                <template #metric>First serve</template>
            </DualStatItem>
            <DualStatItem
                v-if="match.p1.serve1_pts_w && match.p1.serve1_pts && match.p2.serve1_pts_w && match.p2.serve1_pts"
                :p1Value="match.p1.serve1_pts_w" :p1Total="match.p1.serve1_pts" :p2Value="match.p2.serve1_pts_w"
                :p2Total="match.p2.serve1_pts">
                <template #metric>1st serve points won</template>
            </DualStatItem>
            <DualStatItem
                v-if="match.p1.serve2_pts_w && match.p1.serve2_pts && match.p2.serve2_pts_w && match.p2.serve2_pts"
                :p1Value="match.p1.serve2_pts_w" :p1Total="match.p1.serve2_pts" :p2Value="match.p2.serve2_pts_w"
                :p2Total="match.p2.serve2_pts">
                <template #metric>2nd serve points won</template>
            </DualStatItem>
            <DualStatItem v-if="match.p1.bps_saved && match.p1.bps_faced && match.p2.bps_saved && match.p2.bps_faced"
                :p1Value="match.p1.bps_saved" :p1Total="match.p1.bps_faced" :p2Value="match.p2.bps_saved"
                :p2Total="match.p2.bps_faced">
                <template #metric>Break points saved</template>
            </DualStatItem>
            <v-row>
                <v-col class="text-center font-bold">
                    RETURN STATS
                </v-col>
                <v-divider thickness="3" />
            </v-row>
            <DualStatItem v-if="match.p1.ret1_w && match.p1.ret1 && match.p2.ret1_w && match.p2.ret1"
                :p2Value="match.p2.ret1_w" :p2Total="match.p2.ret1" :p1Value="match.p1.ret1_w" :p1Total="match.p1.ret1">
                <template #metric>1st serve return points won</template>
            </DualStatItem>
            <DualStatItem v-if="match.p1.ret2_w && match.p1.ret2 && match.p2.ret2_w && match.p2.ret2"
                :p1Value="match.p1.ret2_w" :p1Total="match.p1.ret2" :p2Value="match.p2.ret2_w" :p2Total="match.p2.ret2">
                <template #metric>2nd serve return points won</template>
            </DualStatItem>
            <DualStatItem
                v-if="match.p1.bps_converted && match.p1.bp_opps && match.p2.bps_converted && match.p2.bp_opps"
                :p1Value="match.p1.bps_converted" :p1Total="match.p1.bp_opps" :p2Value="match.p2.bps_converted"
                :p2Total="match.p2.bp_opps">
                <template #metric>Break points converted</template>
            </DualStatItem>
            <v-row>
                <v-col class="text-center font-bold">
                    POINT STATS
                </v-col>
                <v-divider thickness="3" />
            </v-row>
            <DualStatItem v-if="match.p1.net_w && match.p1.net && match.p2.net_w && match.p2.net"
                :p1Value="match.p1.net_w" :p1Total="match.p1.net" :p2Value="match.p2.net_w" :p2Total="match.p2.net">
                <template #metric>Net points won</template>
            </DualStatItem>
            <StatItem v-if="match.p1.winners && match.p2.winners" :p1="match.p1.winners" :p2="match.p2.winners">
                <template #metric>Winners</template>
            </StatItem>
            <StatItem v-if="match.p1.ues && match.p2.ues" :p1="match.p1.ues" :p2="match.p2.ues" low>
                <template #metric>Unforced errors</template>
            </StatItem>
            <DualStatItem
                v-if="match.p1.serve1_pts_w && match.p1.serve1_pts && match.p1.serve2_pts_w && match.p1.serve2_pts && match.p2.serve1_pts_w && match.p2.serve1_pts && match.p2.serve2_pts_w && match.p2.serve2_pts"
                :p1Value="match.p1.serve1_pts_w + match.p1.serve2_pts_w"
                :p1Total="match.p1.serve1_pts + match.p1.serve2_pts"
                :p2Value="match.p2.serve1_pts_w + match.p2.serve2_pts_w"
                :p2Total="match.p2.serve1_pts + match.p2.serve2_pts">
                <template #metric>Service points won</template>
            </DualStatItem>
            <DualStatItem
                v-if="match.p1.ret1_w && match.p1.ret1 && match.p1.ret2_w && match.p1.ret2 && match.p2.ret1_w && match.p2.ret1 && match.p2.ret2_w && match.p2.ret2"
                :p1Value="match.p1.ret1_w + match.p1.ret2_w" :p1Total="match.p1.ret1 + match.p1.ret2"
                :p2Value="match.p2.ret1_w + match.p2.ret2_w" :p2Total="match.p2.ret1 + match.p2.ret2">
                <template #metric>Return points won</template>
            </DualStatItem>
            <StatItem
                v-if="match.p1.serve1_pts_w && match.p1.serve2_pts_w && match.p2.serve1_pts_w && match.p2.serve2_pts_w && match.p1.ret1_w && match.p1.ret2_w && match.p2.ret1_w && match.p2.ret2_w"
                :p1="match.p1.serve1_pts_w + match.p1.serve2_pts_w + match.p1.ret1_w + match.p1.ret2_w"
                :p2="match.p2.serve1_pts_w + match.p2.serve2_pts_w + match.p2.ret1_w + match.p2.ret2_w" percent>
                <template #metric>Total points won</template>
            </StatItem>
            <v-row>
                <v-col v-if="match.p1.max_speed_kph" class="text-center font-bold">
                    SERVICE SPEED
                </v-col>
                <v-divider thickness="3" />
            </v-row>
            <ServiceStatItem v-if="match.p1.max_speed_kph && match.p2.max_speed_kph" :p1kph="match.p1.max_speed_kph"
                :p2kph="match.p2.max_speed_kph">
                <template #metric>Max Speed</template>
            </ServiceStatItem>
            <ServiceStatItem v-if="match.p1.avg_sv1_kph && match.p2.avg_sv1_kph" :p1kph="match.p1.avg_sv1_kph"
                :p2kph="match.p2.avg_sv1_kph">
                <template #metric>1st serve average speed</template>
            </ServiceStatItem>
            <ServiceStatItem v-if="match.p1.avg_sv2_kph && match.p2.avg_sv2_kph" :p1kph="match.p1.avg_sv2_kph"
                :p2kph="match.p2.avg_sv2_kph">
                <template #metric>2nd serve average speed</template>
            </ServiceStatItem>
        </v-container>
    </v-sheet>
    <v-sheet v-else class="w-5/6 md:w-8/12 lg:w-1/2 mx-auto my-10 bg-transparent">
        <Title>
            <template #title>{{ unencodeName(name) }} {{ year }} {{ matchId }}</template>
        </Title>
        <Loading :loading>
            <template #none>No data available</template>
        </Loading>
    </v-sheet>
</template>
