// client/src/components2/ScoreBox.jsx
import { Card, Col, Row, Tag } from "antd";
import { CheckCircleTwoTone } from "@ant-design/icons";
import ScoreItem from "../Global/ScoreItem";

export default function ScoreBox({ p1, p2, winner }) {
  const set = Array.from({ length: 5 }, (_, i) => i);
  const entryInfo = (entry) => {
    if (entry.seed && entry.status) {
      return `(${entry.seed} ${entry.status})`;
    } else if (entry.seed) {
      return `(${entry.seed})`;
    } else if (entry.status) {
      return `(${entry.status})`;
    }
  };
  return (
    <Card>
      <Row className="mb-2">
        <Col className="flex items-center" span={15}>
          {p1.player.player.full_name}
        </Col>
        <Col span={2}>
          <small>{entryInfo(p1.player)}</small>
        </Col>
        <Col span={2} className="flex items-center">
          {p1.player.player.id === winner ? (
            <CheckCircleTwoTone twoToneColor="#52c41a" />
          ) : p1.incomplete ? (
            <Tag color="#f5222d">{p1.incomplete}</Tag>
          ) : null}
        </Col>
        <Col span={5} className="flex justify-end">
          <ScoreItem score={p1} />
        </Col>
      </Row>
      <Row className="mb-2">
        <Col className="flex items-center" span={15}>
          {p2.player.player.full_name}
        </Col>
        <Col span={2}>
          <small>{entryInfo(p2.player)}</small>
        </Col>
        <Col span={2} className="flex items-center">
          {p2.player.player.id === winner ? (
            <CheckCircleTwoTone twoToneColor="#52c41a" />
          ) : p2.incomplete ? (
            <Tag color="#f5222d">{p2.incomplete}</Tag>
          ) : null}
        </Col>
        <Col span={5} className="flex justify-end">
          <ScoreItem score={p2} />
        </Col>
      </Row>
    </Card>
  );
}

// client/src/components/Match/ScoreBox.vue
<script setup>
import { CheckCircleTwoTone } from '@ant-design/icons-vue'
import { getEntry } from '@/utils/functions'
import { COLOURS } from '@/utils/variables'

const props = defineProps(['p1', 'p2', 'winner'])
</script>

<template>
  <a-config-provider :theme="{ components: { Card: { colorBgContainer: 'transparent' } } }">
    <a-card class="border-zinc-500">
      <a-row class="mb-2">
        <a-col :span="15">{{ p1.player.player.full_name }}</a-col>
        <a-col :span="2"
          ><small>{{ getEntry(p1.player) }}</small></a-col
        >
        <a-col :span="2">
          <CheckCircleTwoTone
            v-if="p1.player.player.id === winner"
            :twoToneColor="COLOURS.green600"
          />
          <a-tag v-if="p1.incomplete" :color="COLOURS.red600">{{ p1.incomplete }}.</a-tag>
        </a-col>
        <a-col :span="5" class="flex justify-end">
          <ScoreItem :score="p1" />
        </a-col>
      </a-row>
      <a-row class="mt-2">
        <a-col :span="15">{{ p2.player.player.full_name }}</a-col>
        <a-col :span="2"
          ><small>{{ getEntry(p2.player) }}</small></a-col
        >
        <a-col :span="2">
          <CheckCircleTwoTone
            v-if="p2.player.player.id === winner"
            :twoToneColor="COLOURS.green600"
          />
          <a-tag v-if="p2.incomplete" :color="COLOURS.red600">{{ p2.incomplete }}.</a-tag>
        </a-col>
        <a-col :span="5" class="flex justify-end">
          <ScoreItem :score="p2" />
        </a-col>
      </a-row>
    </a-card>
  </a-config-provider>
</template>
