// client2/src/components/Event/ResultCard.jsx
import { Avatar, Card, Col, Image, Row, Tag } from "antd";
import { CheckCircleTwoTone } from "@ant-design/icons";
import { encodeName, formatDate, formatTime } from "../../utils/utils";
import { useParams } from "react-router";
import { Link } from "react-router-dom";
import PlayerItem from "../Global/PlayerItem";
import ScoreItem from "../Global/ScoreItem";

export default function ResultCard({ match }) {
  const { tname, tid, year, eid } = useParams();

  const title = (
    <div>
      {match.date ? <div>{formatDate(match.date)}</div> : null}
      {match.court && <div>{match.court}</div>}
    </div>
  );

  const extra = (
    <div>
      {match.duration_mins ? (
        <div className="text-right">{formatTime(match.duration_mins)}</div>
      ) : null}
      {match.umpire && <div className="text-right">{match.umpire.id}</div>}
    </div>
  );

  const entryInfo = (entry) => {
    if (entry.seed && entry.status) {
      return `(${entry.seed} ${entry.status})`;
    } else if (entry.seed) {
      return `(${entry.seed})`;
    } else if (entry.status) {
      return `(${entry.status})`;
    }
  };

  const actions = [
    !match.incomplete && (
      <Tag className="mx-auto bg-transparent border-zinc-300">
        <Link
          to={`/tournaments/${tname}/${tid}/${year}/${eid}/${match.match_no}`}
          className="!text-zinc-300"
        >
          Stats
        </Link>
      </Tag>
    ),
    match.incomplete !== "B" && (
      <Tag className="mx-auto bg-transparent border-zinc-300">
        <Link
          to={`/h2h/${encodeName(match.winner.player.player.full_name)}/${
            match.winner.player.player.id
          }/${encodeName(match.loser.player.player.full_name)}/${
            match.loser.player.player.id
          }`}
          className="!text-zinc-300"
        >
          H2H
        </Link>
      </Tag>
    ),
  ];

  return (
    <>
      <Card
        title={title}
        extra={extra}
        actions={actions}
        className="h-full flex flex-col justify-between p-1"
      >
        <Row className="mb-2">
          <Col span={19}>
            <Row className="items-center">
              <PlayerItem
                player={match.winner.player.player}
                entry={entryInfo(match.winner.player)}
              />
            </Row>
          </Col>
          <Col span={2}>
            <CheckCircleTwoTone twoToneColor="#52c41a" />
          </Col>
          <Col className="flex" span={3}>
            <ScoreItem score={match.winner} />
          </Col>
        </Row>
        <Row className="mt-2">
          <Col span={19}>
            <Row className="items-center">
              {match.loser ? (
                <PlayerItem
                  player={match.loser.player.player}
                  entry={entryInfo(match.loser.player)}
                />
              ) : (
                <>
                  <Col span={6} />
                  <Col span={18}>BYE</Col>
                </>
              )}
            </Row>
          </Col>
          <Col span={2}>
            {match.loser?.incomplete && (
              <Tag color="#f5222d">{match.loser.incomplete}</Tag>
            )}
          </Col>
          <Col className="flex" span={3}>
            {match.loser && <ScoreItem score={match.loser} />}
          </Col>
        </Row>
      </Card>
    </>
  );
}

// th/components/events/result-card.vue
<script setup lang="ts">
const { match } = defineProps<{ match: ResultsMatchType }>()
const name = useRouteParams<string>("name")
const id = useRouteParams<string>("id")
const eid = useRouteParams<string>("eid")
const year = useRouteParams<string>("year")

const sets = computed(() => {
  const filteredSets = match.winner.sets.filter(set => set !== null)
  return filteredSets.length
})
</script>

<template>
  <u-page-card
    highlight
    :ui="{ body: 'w-full', title: 'text-sm' }"
  >
    <template #title>
      <div class="flex flex-col">
        <div class="flex justify-between">
          <span v-if="match.date">{{ match.date }}</span>
          <span class="justify-self-end">{{ match.duration ?? "00:00" }}</span>
        </div>
        <div class="flex justify-between">
          <div v-if="match.court">{{ match.court }}</div>
          <div v-if="match.umpire">
            <umpire-link :umpire="match.umpire" />
          </div>
        </div>
      </div>
    </template>

    <template #description>
      <div class="grid grid-flow-col grid-rows-2 items-center gap-2 mt-5">
        <player-avatar :player="match.winner" />
        <player-avatar :player="match.loser" />
        <small>{{ match.winner.seed || match.winner.status ? `(${match.winner.seed ?? ""}${match.winner.status ?? ""})` : "" }}</small>
        <small>{{ match.loser.seed || match.loser.status ? `(${match.loser.seed ?? ""}${match.loser.status ?? ""})` : "" }}</small>
        <u-icon
          :name="ICONS.success"
          class="text-success-600 dark:text-success-300 text-lg"
        />
        <div>
          <u-badge
            v-if="match.loser.incomplete"
            color="error"
            :label="`${match.loser.incomplete}.`"
          />
        </div>
        <div :class="`grid grid-cols-${sets}`">
          <template
            v-for="(set, index) in match.winner.sets"
            :key="`winner-${index}`"
          >
            <!--prettier-ignore-->
            <span v-if="set" class="mr-2">
              {{ set }}<sup v-if="match.winner.tbs[index]">{{ match.winner.tbs[index] }}</sup>
            </span>
          </template>
        </div>
        <div :class="`grid grid-cols-${sets}`">
          <template
            v-for="(set, index) in match.loser.sets"
            :key="`loser-${index}`"
          >
            <!--prettier-ignore-->
            <span v-if="set" class="mr-2">
              {{ set }}<sup v-if="match.loser.tbs[index]">{{ match.loser.tbs[index] }}</sup>
          </span>
          </template>
        </div>
      </div>
    </template>

    <template #footer>
      <u-button-group size="sm">
        <u-button
          label="Stats"
          :icon="ICONS.stats"
          :to="{ name: 'match', params: { name, id, year, eid, mid: match.mid } }"
          :disabled="!!match.incomplete"
        />
        <u-button
          label="H2H"
          :icon="ICONS.h2h"
          :to="{ name: 'h2h-players', params: { p1Name: encodeName(match.winner.name), p1Id: match.winner.id, p2Name: encodeName(match.loser.name), p2Id: match.loser.id } }"
        />
      </u-button-group>
    </template>
  </u-page-card>
</template>
