// client2/src/components/Archive/Archive.jsx
import { useState } from "react";
import { Helmet } from "react-helmet-async";
import { useQuery } from "@apollo/client";
import { DateTime } from "luxon";
import { Row, Col, Select } from "antd";
import { GET_ARCHIVE } from "../../services/EventService";
import Title from "../Global/Title";
import Loading from "../Global/Loading";
import EventCard from "../Global/EventCard";

export default function Archive() {
  const [selectedYear, setSelectedYear] = useState(DateTime.now().year);
  const years = [
    {
      label: 2018,
      value: 2018,
    },
    {
      label: 2024,
      value: 2024,
    },
  ];

  const handleChange = (value) => setSelectedYear(value);

  const { loading, error, data } = useQuery(GET_ARCHIVE, {
    variables: { year: selectedYear },
  });
  if (error) console.error(error);

  return (
    <>
      <Helmet>
        <title>Results Archive | TennisHistory</title>
      </Helmet>
      <Row align="middle" justify="space-between" className="mb-5">
        <Col xs={24} sm={20} xl={22}>
          <Title title="Results Archive" />
        </Col>
        <Col xs={24} sm={4} xl={2}>
          <Select
            showSearch
            options={years}
            onChange={handleChange}
            defaultValue={selectedYear}
            className="w-[100%] text-center"
            size="large"
          />
        </Col>
      </Row>
      {data && (
        <Row justify="space-evenly" align="stretch" gutter={[0, 32]}>
          {data.events.map((event) => {
            return (
              <Col xs={24} sm={11} md={7} xl={5} key={event.id}>
                <EventCard event={event} />
              </Col>
            );
          })}
        </Row>
      )}
      {!data && <Loading loading={loading} none="No data available" />}
    </>
  );
}

// client/src/views/Archive/Archive.vue
<script setup lang="ts">
import { ref, watch, watchEffect, type Ref } from 'vue';
import apolloClient from '@/apollo';
import { provideApolloClient, useQuery } from '@vue/apollo-composable';
import { DateTime } from 'luxon'
import { getEventsByYear } from '@/services/EventService';
import type { Event } from '@/utils/interfaces';
import Title from '@/components/Global/Title.vue'
import Loading from '@/components/Global/Loading.vue'
import EventCard from '@/components/Global/EventCard.vue';

provideApolloClient(apolloClient)

const years = Array.from({ length: (DateTime.now().year + 1) - 1968 }, (_, index) => DateTime.now().year - index)
const searchYear: Ref<number> = ref(DateTime.now().year)
const events: Ref<Event[]> = ref([])
const load = ref(false)

const updateResults = () => {
    load.value = true

    const { query, variables } = getEventsByYear(searchYear.value)
    const { result, loading, error } = useQuery(query, variables)

    watch(result, (newResult) => {
        if (newResult) {
            events.value = newResult.events
            load.value = false
        }
    }, { immediate: true })

    watch(loading, (newLoad) => load.value = newLoad)

    watch(error, (newError) => {
        if (newError) console.error(newError)
    }, { immediate: true })
}

watchEffect(() => updateResults())
</script>

<template>
    <v-sheet class="bg-transparent m-16 w-75 pa-3 mx-auto">
        <v-container>
            <v-row class="flex items-center">
                <v-col>
                    <Title>
                        <template #title>Results Archive</template>
                    </Title>
                </v-col>
                <v-col cols="12" sm="3">
                    <v-combobox class="text-zinc-300" variant="underlined" v-model="searchYear" :items="years" />
                </v-col>
            </v-row>
            <v-row>
                <v-col v-if="events.length > 0" v-for="event in events" :key="event.id" cols="12" sm="4" xl="3">
                    <EventCard :event />
                </v-col>
                <v-col v-else>
                    <Loading :loading="load">
                        <template #none>No data available</template>
                    </Loading>
                </v-col>
            </v-row>
        </v-container>
    </v-sheet>
</template>
